/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutData { 'bio' : string, 'timeline' : Array<TimelineEntry> }
export interface AddItemRequest {
  'title' : string,
  'contentType' : ContentType,
  'date' : string,
  'tags' : Array<string>,
  'description' : string,
  'externalUrl' : [] | [string],
  'fileUrl' : [] | [string],
}
export type ContactId = bigint;
export interface ContactRequest {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : ContactId,
  'subject' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface ContentItem {
  'id' : ItemId,
  'title' : string,
  'contentType' : ContentType,
  'date' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'externalUrl' : [] | [string],
  'fileUrl' : [] | [string],
}
export type ContentType = string;
export type ItemId = bigint;
export type LoginResult = { 'ok' : Token } |
  { 'err' : string };
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_2 = { 'ok' : ContactSubmission } |
  { 'err' : string };
export type Result_3 = { 'ok' : Array<ContactSubmission> } |
  { 'err' : string };
export type Result_4 = { 'ok' : ContentItem } |
  { 'err' : string };
export interface TimelineEntry { 'year' : string, 'description' : string }
export type Timestamp = bigint;
export type Token = string;
export interface UpdateItemRequest {
  'id' : ItemId,
  'title' : string,
  'contentType' : ContentType,
  'date' : string,
  'tags' : Array<string>,
  'description' : string,
  'externalUrl' : [] | [string],
  'fileUrl' : [] | [string],
}
export interface _SERVICE {
  'addItem' : ActorMethod<[Token, AddItemRequest], Result_4>,
  'adminLogin' : ActorMethod<[string], LoginResult>,
  'deleteContact' : ActorMethod<[Token, ContactId], Result_1>,
  'deleteItem' : ActorMethod<[Token, ItemId], Result>,
  'getAbout' : ActorMethod<[], AboutData>,
  'getContacts' : ActorMethod<[Token], Result_3>,
  'getItem' : ActorMethod<[ItemId], [] | [ContentItem]>,
  'getItemsByType' : ActorMethod<[ContentType], Array<ContentItem>>,
  'submitContact' : ActorMethod<[ContactRequest], Result_2>,
  'updateAbout' : ActorMethod<[Token, AboutData], Result_1>,
  'updateItem' : ActorMethod<[Token, UpdateItemRequest], Result>,
  'verifyToken' : ActorMethod<[Token], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];