/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Token = IDL.Text;
export const ContentType = IDL.Text;
export const AddItemRequest = IDL.Record({
  'title' : IDL.Text,
  'contentType' : ContentType,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'externalUrl' : IDL.Opt(IDL.Text),
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const ItemId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContentItem = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'externalUrl' : IDL.Opt(IDL.Text),
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const Result_3 = IDL.Variant({ 'ok' : ContentItem, 'err' : IDL.Text });
export const LoginResult = IDL.Variant({ 'ok' : Token, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const ContactId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(ContactSubmission),
  'err' : IDL.Text,
});
export const ContactRequest = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Result_1 = IDL.Variant({
  'ok' : ContactSubmission,
  'err' : IDL.Text,
});
export const UpdateItemRequest = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'externalUrl' : IDL.Opt(IDL.Text),
  'fileUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func([Token, AddItemRequest], [Result_3], []),
  'adminLogin' : IDL.Func([IDL.Text], [LoginResult], []),
  'deleteItem' : IDL.Func([Token, ItemId], [Result], []),
  'getContacts' : IDL.Func([Token], [Result_2], []),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(ContentItem)], ['query']),
  'getItemsByType' : IDL.Func([ContentType], [IDL.Vec(ContentItem)], ['query']),
  'submitContact' : IDL.Func([ContactRequest], [Result_1], []),
  'updateItem' : IDL.Func([Token, UpdateItemRequest], [Result], []),
  'verifyToken' : IDL.Func([Token], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Token = IDL.Text;
  const ContentType = IDL.Text;
  const AddItemRequest = IDL.Record({
    'title' : IDL.Text,
    'contentType' : ContentType,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'externalUrl' : IDL.Opt(IDL.Text),
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const ItemId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContentItem = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'externalUrl' : IDL.Opt(IDL.Text),
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const Result_3 = IDL.Variant({ 'ok' : ContentItem, 'err' : IDL.Text });
  const LoginResult = IDL.Variant({ 'ok' : Token, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const ContactId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(ContactSubmission),
    'err' : IDL.Text,
  });
  const ContactRequest = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : ContactSubmission, 'err' : IDL.Text });
  const UpdateItemRequest = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'externalUrl' : IDL.Opt(IDL.Text),
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addItem' : IDL.Func([Token, AddItemRequest], [Result_3], []),
    'adminLogin' : IDL.Func([IDL.Text], [LoginResult], []),
    'deleteItem' : IDL.Func([Token, ItemId], [Result], []),
    'getContacts' : IDL.Func([Token], [Result_2], []),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(ContentItem)], ['query']),
    'getItemsByType' : IDL.Func(
        [ContentType],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'submitContact' : IDL.Func([ContactRequest], [Result_1], []),
    'updateItem' : IDL.Func([Token, UpdateItemRequest], [Result], []),
    'verifyToken' : IDL.Func([Token], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };